language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

# lock distro so new future defaults will not break the build
dist: precise

# also test against HHVM, but require "trusty" and ignore errors
matrix:
  include:
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer install

script:
  - ./vendor/bin/phpunit -v --coverage-text --coverage-clover=./build/logs/clover.xml

after_script:
  - if [ -f ./build/logs/clover.xml ]; then travis_retry composer require satooshi/php-coveralls --no-interaction --update-with-dependencies; fi
  - if [ -f ./build/logs/clover.xml ]; then php vendor/bin/coveralls -v; fi
